### ISSUE TITLE
Add support for versatile-block-paras

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/htmlmaker_js#17]
Add support for paragraphs that can appear in multiple types of blocks. See https://github.com/macmillanpublishers/bookmaker/blob/master/core/htmlmaker/wordtohtml.xsl#L26

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
The js is updated and deployed, assigning this task to Erica for the Word-template repo review
