### ISSUE TITLE
Read paragraph lists from external file

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/htmlmaker_js#20]
Create a file to maintain the various paragraph lists in htmltohtmlbook.js. E.g., move the explicit lists of paras from line 34 to line 241 to a separate file, and then read that file into each array.

**Comment by MacmillanWorkflows** [comment]
➤ Nellie McKesson commented:
Ultimately my goal is that we'll export this new file from the styles spreadsheet, based on new columns that list whether each style falls into one of these groups of paragraphs.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
I see, this makes a lot of sense!  Is json your preferred way to store the lists?

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
This is reviewed & deployed!  Closing
