### ISSUE TITLE
Soft return in Tor.com copyright statement is not captured in htmlmaker_js html

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/htmlmaker_js#38]
In several Tor.com manuscripts this copyright statement is broken up like so, via soft return:
"Tor® is a registered trademark of
 Macmillan Publishing Group, LLC."
Without the soft return it all goes on one line, and "ofMacmillan" becomes one word :(

example:  https://www.dropbox.com/s/rzxltjitqfeamjr/9780765395436_MNU.docx?dl=0

**Comment by mattretzer** [comment]
I have [another file ](https://www.dropbox.com/s/4ohoowpqvzswnnu/9780765395733_MNU.docx?dl=0)with a soft return being ignored in htmlmaker_js, this time in a dedication; again it created a run-on word (the js is on the in the screengrab below): 
![screen shot 2017-05-22 at 10 27 26 am](https://cloud.githubusercontent.com/assets/7025870/26313538/2f576216-3ed9-11e7-971f-2b4737f23d44.png)

**Comment by mattretzer** [comment]
Another soft return, this one in an Epigraph Source para..  not sure this is the best way to style this regardless, just another example of soft-return in use off of the copyright page:
https://www.dropbox.com/s/9ncrhlzgokye35b/9780765397133_MNU_ctnp-epigraph.docx?dl=0

**Comment by MacmillanWorkflows** [comment]
➤ 11976868364439 commented:

Soft returns should get preserved directly in the convert.js script, in htmlmaker_js

**Comment by MacmillanWorkflows** [comment]
➤ 9491251705208 commented:

Thanks for the tip!  Was just poring over that file 🙂
