### ISSUE TITLE
discrepancy in ebook with backad position/sequence

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/htmlmaker_js#39]
These may be desired behaviors, but noting them regardless, as discrepancies from the xsl-html-conversion toolchain:
- When using Back-ad Section Start, there it gets it's own 'Ad' entry in the ncx for the ebook.
- In the case of [this file](https://www.dropbox.com/s/zrln24ftyd9c5cp/9780765389831_MNU.docx?dl=0), the back-ad was manually added in the manuscript - unlike the automatically inserted back-ads, which are inserted after the ATA and adcard, this one was inserted before the ATA (by default). We may want to deliberately set the placement/sequence in which a section-back-ad falls in the epub, unless we want it prior to the ATA

**Comment by mattretzer** [comment]
I am renaming this issue and splitting it into 2 parts.

**Comment by mattretzer** [comment]
Regarding the relative placement of the Section-Back-Ad in the epub: 

I've seen several methods used to style Bobads in our original test manuscripts; in one it was just at the end of another section; in one there is a bobad-Title styled-para to indicate a bobad section, in one it was in it's own section with a ChapTitleNonprinting :(.  

It looks like it was supposed to be indicated with a BOB Ad Title (bobt) styled para, which was then moved to back of book via [this code](https://github.com/macmillanpublishers/bookmaker_addons/blob/master/epubmaker_preprocessing.rb#L299-L300) in bookmaker_addons.

• From what I can tell (?) the above code will not act upon a Section-Back-Ad section unless it also has a BOB Ad head or other bobad style, which will not necessarily be the case; so we would need to edit this. 
• (we may want to look at all of the "localMoveSection" method calls in [epubmaker_preprocessing.rb ](https://github.com/macmillanpublishers/bookmaker_addons/blob/master/epubmaker_preprocessing.rb)and see if this might be an issue with any other items.

**Comment by mattretzer** [comment]
We need to make sure our section has this class, or this contains our section's class [here](https://github.com/macmillanpublishers/bookmaker_assets/blob/master/sections.json#L88-L91).
And we should go over the rest of these to make sure we don't have the same issue: https://github.com/macmillanpublishers/bookmaker_addons/blob/master/epubmaker_preprocessing.rb#L296-L318

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

This will be resolved by this PR (pending review)
https://github.com/macmillanpublishers/htmlmaker_js/pull/64
which includes the class update for Section-Backads in the style-config.json.  There are no other class mismatches for the relevant sections between sections.json and style-config.json
