### ISSUE TITLE
epub has ncx entries for both Section-ExcerptOpener And Section-ExcerptChapter

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/htmlmaker_js#41]
This is an expected behavior when using section starts; just noting another discrepancy from epub output from htmlmaker_js toolchain versus xsl toolchain so we can decide whether we want to change it.
File [here](https://www.dropbox.com/s/wap0f4al3cm9j9n/9781250136749_MNU.docx?dl=0).

**Comment by mattretzer** [comment]
(In the XSL version, the Excerpt Opener is styled as ChapTitleNonPrinting, so it has an ncx entry ; but the Section-Excerpt-Chapter does not. That would probably be our ideal outcome for the js too, unless there are cases where Section-Excerpt-Chapter exists without Section-Excerpt-Opener. 

This is related to this issue: https://github.com/macmillanpublishers/htmlmaker_js/issues/47

**Comment by MacmillanWorkflows** [comment]
➤ 9491251705208 commented:

We should suppress the SEC ncx entry; we think notoc class will do thetrick butwill need to test.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Submitted PR for this: https://github.com/macmillanpublishers/bookmaker_addons/pull/166

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

approved, merged & deployed
