### ISSUE TITLE
ChapterNumber without ChapterTitle is not converted to h1

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/htmlmaker_js#42]
Found this via [this test MS](https://www.dropbox.com/s/6n100b56dq3laws/9781250105868_MNU.docx?dl=0), which was deliberately styled to test Section Starts featuring ChapNumbers _without_ ChapTitles:
- auto-numbering was NOT turned on, as expected
However:
- Instead of Chap Numbers being converted to H1's, ChapTitleNonPrinting paras were generated as the H1, and ChapNumbers became standard `<p>` elements with .ChapNumbercn class. 

In the epub of course this resulted in ChapNumbers not getting reverse links to the ncx, and in the pdf it looks like they weren't styled at all (because they weren't h1's)

Example from the html:
```
    <section data-type="chapter" id="sectidb1hg3" class="">
        <header>
            <h1>Chapter 1</h1></header>
        <h1 class="Nonprinting">Chapter 1</h1>
        <p class="ChapNumbercn" id="idtv6w6tysq">Chapter One</p>
```

**Comment by MacmillanWorkflows** [comment]
➤ 11976868364439 commented:

1) Chap Number should be added to the headingparas list in htmlmaker_js: https://github.com/macmillanpublishers/htmlmaker_js/blob/master/style_config.json

2) The code here: https://github.com/macmillanpublishers/htmlmaker_js/blob/master/lib/htmltohtmlbook.js#L567 should be made more generic. It should read paragraph lists from the configurable JSON and create selectors based on that (may need to add new JSON fields).

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

submitted PR for this: https://github.com/macmillanpublishers/htmlmaker_js/pull/68

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

merge conflict needs resolution

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

pulled in master, resolved conflicts
