### ISSUE TITLE
[2] htmlmaker-js stripped out improperly styled hyperlink in back-ad 

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/htmlmaker_js#46]
In [this manuscript](https://www.dropbox.com/s/0a0nx7bzoo6p2ps/9781250105868_MNU_NEW.docx?dl=0), in the backad there is a hyperlink styled with native Word character style 'hyperlink'.  In the xsl conversion, the resulting html includes the span as shown in the code below, but in the js-converted html, the whole hyperlink element is missing (including linked text):
`<p class="BOBAdLevel-2Subheadbobh2">For more information, visit <span class="spanhyperlinkurl">www.amarthur.blogspot.com</span></p>`

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

submitted this PR for review: https://github.com/macmillanpublishers/htmlmaker_js/pull/66

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

should re-test as per Nellie's comment

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

1.5 hrs

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

re-reviewed, tested, merged.
