### ISSUE TITLE
Section-Back-Ad automatically puts 'Ad' entry into epub ncx

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/htmlmaker_js#49]
If we wanted to globally turn this off, looks like we could add that in addons [here](https://github.com/macmillanpublishers/bookmaker_addons/blob/master/epubmaker_preprocessing.js#L155-L156).

If we want the user to be able to toggle whether the Ad shows up in the TOC, maybe this is where we add the ability to use the content of the SectionStart para as a processing instruction? Looks like bookmaker-pi's are how it was done before.

Example manuscripts:
https://www.dropbox.com/s/e7df3tatznvn5ly/9781250128614_MNU_NEW.docx?dl=0
https://www.dropbox.com/s/1wm499esgg6q4fp/9781250119971_MNU_NEW.docx?dl=0

**Comment by MacmillanWorkflows** [comment]
➤ 9491251705208 commented:

We can toggle this off with a notoc style.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Submitted PR for this: https://github.com/macmillanpublishers/bookmaker_addons/pull/166

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

approved, merged & deployed
