### ISSUE TITLE
[2] Section-Back-Ad became section data-type 'Appendix' in html, and generated leading blank page in pdf

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/htmlmaker_js#50]
The former item (Section-Back-Ad style converting to Section data-type="Appendix") may or may not be expected in htmlmaker_js; the latter (the blank page) is an expected behavior for section-starts but may not be a desired behavior for back-ads in pdfs. 
It was a difference found in [this manuscript](https://www.dropbox.com/s/cc3tgm6bgi022mr/9780765389831_MNU_ctnp-removed.docx?dl=0) in testing htmlmaker-js.

**Comment by MacmillanWorkflows** [comment]
➤ 9491251705208 commented:

We should add in the pdf-css - a new definition for Section-Back-Ad with page-break-before: always; instead of page-break-before: right;

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

1.5 hrs

**Comment by MacmillanWorkflows** [comment]
➤ erica.warren commented:

[Matthew Retzer](https://app.asana.com/0/9492427432407/9492427432407) Started this, was planning on doing a bunch of CSS things together but if you think I should open separate pull requests for each, please let me know and I can do that.

**Comment by MacmillanWorkflows** [comment]
➤ erica.warren commented:

[Matthew Retzer](https://app.asana.com/0/9492427432407/9492427432407) Please review the PR for this issue: https://github.com/macmillanpublishers/bookmaker_assets/pull/73

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

approved!
