### ISSUE TITLE
[6] Fullpage backads are getting vertically compressed and overlapping top margin

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/htmlmaker_js#51]
See good (left) and bad (right) versions of same back-ad below:
Example manuscript:
https://www.dropbox.com/s/e7df3tatznvn5ly/9781250128614_MNU_NEW.docx?dl=0

![screen shot 2017-05-25 at 3 38 45 pm](https://cloud.githubusercontent.com/assets/7025870/26467422/8246f318-4160-11e7-84b4-0c35f25a5a5c.png)

Also [this one](https://www.dropbox.com/s/cc3tgm6bgi022mr/9780765389831_MNU_ctnp-removed.docx?dl=0), though the backad is getting squished and offset-upwards in the xsl-converted of this version too; but the upward offset is greater in the js-converted one.

![screen shot 2017-05-25 at 2 21 30 pm](https://cloud.githubusercontent.com/assets/7025870/26467524/f6a43a0e-4160-11e7-8a62-b27f09f16f05.png)

NOTE: I saw at least one good example of a full-page illustration working with a js-conversion during testing, with this MS: https://www.dropbox.com/s/obt7cr8hkkc7qwg/9780765395399_MNU.docx?dl=0

**Comment by MacmillanWorkflows** [comment]
➤ 9491251705208 commented:

Haven't investigated, but this could be caused by the reordering of items in figure block as documented in this issue: https://github.com/macmillanpublishers/htmlmaker_js/issues/61

**Comment by mattretzer** [comment]
Update to above comment:  The fix for Issue https://github.com/macmillanpublishers/htmlmaker_js/issues/61 did not resolve this issue.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

6 hrs

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Fixed this, patching Erica's PR with other CSS fixes so this is wrapped up in those (https://github.com/macmillanpublishers/bookmaker_assets/compare/epigraphupdate...eu_csspatch?expand=1#diff-7cb48ba63df5a1fb482ad45c7b88aab1R1495)
