### ISSUE TITLE
Endnotes section gets a non-printing head in htmlmaker_js

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/htmlmaker_js#54]
(Encountered when testing with our [test manuscript](https://www.dropbox.com/s/gwu0qxj1do11coy/bookmaker%20SECTION%20test%20MS%27.doc.docx?dl=0))

In both xsl and js conversion, embedded Endnotes are moved to a section at the end of the html: 
`<section data-type="appendix" class="endnotes">`
However in the xsl conversion this section gets a visible heading:
`<h1 class="BMHeadbmh">Endnotes</h1>`

In the js conversion this section gets a non-printing head:
`<h1 class="Nonprinting">Appendix 1</h1>`

**Comment by MacmillanWorkflows** [comment]
➤ 9491251705208 commented:

Ideally the Endnotes wrapper would be moved from convert.js to htmltohtmlbook.js, and we would have the class match the class for Notes in styleconfig.json.

**Comment by MacmillanWorkflows** [comment]
➤ 9491251705208 commented:

[Nellie McKesson](https://app.asana.com/0/142682204252343/142682204252343): Style_config.json in htmlmaker_js has Section-Notes 'label' as 'Notes', which doesn't match the heading in xsl: 'Endnotes'.  Would you prefer I ... 
1) change style-config.json Notes 'label' to 'Endnotes'?
2) hard code 'Endnotes' as the heading for the auto-generated Endnotes section? or 
3) Just let the heading match the label for htmlmaker_js? ('Notes')

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Submitted PR for this: https://github.com/macmillanpublishers/htmlmaker_js/pull/64

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

approved & merged!
