### ISSUE TITLE
Unnumbered list in htmlmaker_js did not get vertical padding or bullets

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/htmlmaker_js#55]
(Encountered when testing with our [test manuscript](https://www.dropbox.com/s/gwu0qxj1do11coy/bookmaker%20SECTION%20test%20MS%27.doc.docx?dl=0))

One or both of these may be desired outcomes, but noting them as a discrepancy:

In the unnumbered list just prior to the Appendix in our test manuscript: when run by htmlmaker_js, in both pdf and epub output, there are no bullets, & no vertical padding above or below the list.

Here's a screenshot from the epub:
![screen shot 2017-06-06 at 9 48 11 am](https://cloud.githubusercontent.com/assets/7025870/26832389/4d2971b0-4a9d-11e7-87dc-191e414d2e24.png)

Here is the relevant html from the htmlmaker_js:
```
                <p class="ListUnnumul" id="idg98ycqrgh">NIMEY&#x2014;Not In My Election Year</p>
                <p class="ListUnnumul" id="idsbix0un1v">NIMTOO&#x2014;Not In My Term of Office</p>
                <p class="ListUnnumul" id="idw0y9978oa">LULU&#x2014;Locally Undesirable Land Use</p>
                <p class="ListUnnumul" id="id7h0ykmwlf">NOPE&#x2014;Not on Planet Earth</p>
                <p class="ListUnnumul" id="idd8lerkviw">CAVE&#x2014;Citizens Against Virtually Everything</p>
                <p class="ListUnnumul" id="idpnpd182j0">BANANA&#x2014;Build Absolutely Nothing Anywhere Near Anything</p>
```

And here it is in the xsl:
```
                 <ul>
                    <li class="ListUnnumul">
                        <p class="ListUnnumul">NIMEY&#x2014;Not In My Election Year</p>
                    </li>
                    <li class="ListUnnumul">
                        <p class="ListUnnumul">NIMTOO&#x2014;Not In My Term of Office</p>
                    </li>
                    <li class="ListUnnumul">
                        <p class="ListUnnumul">LULU&#x2014;Locally Undesirable Land Use</p>
                    </li>
                    <li class="ListUnnumul">
                        <p class="ListUnnumul">NOPE&#x2014;Not on Planet Earth</p>
                    </li>
                    <li class="ListUnnumul">
                        <p class="ListUnnumul">CAVE&#x2014;Citizens Against Virtually Everything</p>
                    </li>
                    <li class="ListUnnumul">
                        <p class="ListUnnumul">BANANA&#x2014;Build Absolutely Nothing Anywhere Near Anything</p>
                    </li>
                </ul>
```

**Comment by nelliemckesson** [comment]
Lets go ahead and replicate the existing handling. I.E., add listunnumul to the unorderedlistparas (https://github.com/macmillanpublishers/htmlmaker_js/blob/master/style_config.json#L157).

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Submitted a PR for this, here: https://github.com/macmillanpublishers/htmlmaker_js/pull/67

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

merge conflict needs resolution

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

pulled in master, resolved conflict

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

pulled in master, resolved conflicts
