### ISSUE TITLE
[4] Epigraph discrepancies in pdf

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/htmlmaker_js#59]
(Encountered when testing with our[ test manuscript](https://www.dropbox.com/s/gwu0qxj1do11coy/bookmaker%20SECTION%20test%20MS%27.doc.docx?dl=0))

The Epigraph was styled pretty differently in the pdf output from the test manuscript.  In the xsl run, it got enveloped into the Dedication section, whereas in the htmlmaker_js it becomes it's own section: `<section data-type="preface" id="sectid2k8l7" class="epigraph" title="Epigraph">`
But I'm pretty sure that at least the epigraph source is not coming out right in the js version, (its not differentiated from the the rest of the epigraph) and I don't think we should be getting a page number, so we may need to add some pdf css for section.epigraph(data-type="preface")

Screenshot of the pdfs (htmlmaker_js on the left, xsl on the right):

![screen shot 2017-06-06 at 11 16 25 am](https://user-images.githubusercontent.com/7025870/26836887-1020b262-4aaa-11e7-8cf7-32850360a455.png)

**Comment by nelliemckesson** [comment]
Bookmarking this to discuss further.

**Comment by mattretzer** [comment]
Make sure we are passing epubcheck!  Look at styling.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

4 hrs

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

This and other edits to epigraph_updates branch are in a PR for Luigi's review, here:
https://github.com/macmillanpublishers/bookmaker_assets/pull/77

**Comment by MacmillanWorkflows** [comment]
➤ luigi.squillante commented:

approved

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

merged
