### ISSUE TITLE
Paras styled as captions are getting different tags in htmlmaker_js

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/htmlmaker_js#60]
(Encountered when testing with our [test manuscript](https://www.dropbox.com/s/gwu0qxj1do11coy/bookmaker%20SECTION%20test%20MS%27.doc.docx?dl=0))

Here is how a paragraph styles as "Caption (cap)" is tagged in the xsl-output html:
`<figcaption class="Captioncap">This is an image that is missing.</figcaption>`

and here is the same element in htmlmaker_js html:
`<p class="Captioncap" id="idccmtx1922">This is an image that is missing.</p>`

**Comment by nelliemckesson** [comment]
The XSL styling is correct. We should add the conversion after this block: https://github.com/macmillanpublishers/htmlmaker_js/blob/master/lib/htmltohtmlbook.js#L366 . We already source in the caption para list here: https://github.com/macmillanpublishers/htmlmaker_js/blob/master/lib/htmltohtmlbook.js#L48

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

This PR resolves this issue: https://github.com/macmillanpublishers/htmlmaker_js/pull/65
